### ISSUE TITLE
Issue email

### ISSUE THREAD

**Issue by gealberto** [socieboy/forum#12]
Hello ,is possible to configure the job class in  laravel 5.0 ? . although I remove sending mail (email = false ) in forum.php file,  it shows me error when replying to a topic.

**Comment by socieboy** [comment]
Yes is possible!
I think  you can create a folder called Jobs on the App directory, then create a class Job.php with the namespace App\Jobs, then extend the class Command on the App\Commands namespace.
### Job.php
```
<?php
namespace App\Jobs;

class Job extends App\Commands\Job
{

}
```
I think that should do the trick!
