### ISSUE TITLE
Delete Reply Issue

### ISSUE THREAD

**Issue by Teranode** [socieboy/forum#21]
When deleting a reply it uses the table "replies" instead of $prefix . "replies". So having a forum prefix doesn't work.

**Comment by Teranode** [comment]
Also is it possible to have sub-topics? (topic subcategories)

**Comment by socieboy** [comment]
The class Reply extends the class BaseModel, this class take care of the issue adding the prefix to the protected property $table

**Comment by socieboy** [comment]
The forum right now doesn't have support for subtopics, feel free to send a pull request and update the code!

**Comment by Teranode** [comment]
I thought you would have said that however the main problem is in the request, you forgot to put the Database prefix config in the delete reply request.

**Comment by socieboy** [comment]
You mean in the rules right?

**Comment by Teranode** [comment]
yes

**Comment by socieboy** [comment]
We can fix it just calling the prefix key of the config, I'll take care of this thank you!
