### ISSUE TITLE
Replies

### ISSUE THREAD

**Issue by lethality** [socieboy/forum#22]
Hi, firstly, this looks amazing, and just what I need to drop into the Laravel site I'm working on. Only a minor request, I wonder if str_plural could be used on the "replies" count, for the correct "reply" if a post has one reply.

**Comment by socieboy** [comment]
Thank you for using the forum! Good point! I will update that a soon it's possible or feel free to send a pull request with the changes!

**Comment by socieboy** [comment]
Fixed!
