### ISSUE TITLE
undefined method during vendor publish

### ISSUE THREAD

**Issue by z1haze** [socieboy/forum#29]
Hey, am receiving this error when trying to publish the package

Call to undefined method Illuminate\Foundation\Application::bindShared()

I think it changes to app->singleton or something like that. How can we make this work?

**Comment by socieboy** [comment]
What version of Laravel are you using?

**Comment by z1haze** [comment]
5.2 and thank you for the rapid response.

**Comment by z1haze** [comment]
also are you aware that your website with the example has been broken for quite some time? I was worried you stopped supporting this before I ever had a chance to try it.

**Comment by socieboy** [comment]
I was checking my email haha! I haven't update the forum for Laravel 5.2, so it may be the issue!

**Comment by z1haze** [comment]
Well, when could you make it work? im wanting to tinker with this today. I understand if you cant just stop and work on it now. But can you tell me where to look? The issue happens when running vendor:publish so if you could just tell me what files are executed during that time i may be able to get it working.

**Comment by socieboy** [comment]
yes, I don't have pretty much time right now! to work in that, it may could take a couple weeks to me!

**Comment by z1haze** [comment]
Im going through and manually trying to update the package myself.. Seems to be one error after another though :(. but looking in your routes file, is this package not designed to be installed along side a current laravel isntallation? or can I just modifiy the routes file to change from get('/' ... to get('/forums' ?

**Comment by socieboy** [comment]
Yes you can try to fix it and send a pull request!

**Comment by socieboy** [comment]
I think the problem is because laravel 5.2 does'nt have the method bindShared anymore, no sure!

**Comment by z1haze** [comment]
I already fixed that part. But your routes file was getting undefined function get() .. like it required using Route:: im not sure why. but that seems to 'patch' it up

**Comment by socieboy** [comment]
I had to put the in the web middleware of laravel 5.2, get it's a function of laravel

**Comment by z1haze** [comment]
You fixed it?

**Comment by socieboy** [comment]
no!

2016-01-04 13:43 GMT-08:00 z1haze <notifications@github.com>:

**Comment by z1haze** [comment]
no need to shout xD

**Comment by z1haze** [comment]
I got it working. Isn't there a default template for this?

**Comment by socieboy** [comment]
yes, you have to run npm install and gulp, it works with  laravel elixier

2016-01-04 13:45 GMT-08:00 z1haze <notifications@github.com>:

**Comment by z1haze** [comment]
I already use gulp. Where is the css file?

**Comment by z1haze** [comment]
I need whatever I need to add to my gulpfile.. Theres no instructions for that

**Comment by z1haze** [comment]
Nevermind m8, I see you are using LESS

**Comment by socieboy** [comment]
just add mix.less('forum.less') and mixed

2016-01-04 13:55 GMT-08:00 z1haze <notifications@github.com>:

**Comment by z1haze** [comment]
Hey man, again.. I've got all my auth setup.. but when logged in and i navigate to /forum i am still greeted with asking me to login.. It is not recognizing being logged in? How come?
