### ISSUE TITLE
Some updates

### ISSUE THREAD

**Issue by stygiansabyss** [socieboy/forum#33]
Before I start, I want to make it clear, I will be willing to add these and do a PR, but want to make sure you're on board first.

* new events
    * trigger events on conversation start and on best answer selection
* allow editing of existing posts/replies
* order comments from oldest to newest.

Also, not sure why the text for conversations and replies are links that dont actually point to an anchor tag.  Same is true for the reply textarea.  So it keeps forcing the page to the top for no reason.

**Comment by socieboy** [comment]
Hey Hi, thank you.. yes send your PR and I will be working in that with you!

**Comment by stygiansabyss** [comment]
What I have so far:

* Fixed en lang file a bit
* added home button to the left of the start conversation button for quickly going to the index page
* Updated a few parts of the styles
* Added the edit button into the reply drop down
* Fixed the "everything is a link" bug when viewing a conversation
* added NewConversation and BestAnswer events

A few questions though.  

I see you store the details of conversations and replies as HTML in the database.  This may be a bad idea since it means you cant escape the output on the page.  I would like to change this to storing the markdown, then converting it when displaying on the web page.  This would allow users to edit exactly what they submitted and still allow us to handle the front end better.

While adding the events, I noticed you only trigger events if the config is set to broadcasting is true.  I think this could be a mistake.  Events should be thrown at all times.  While I may not want to broadcast, I could want to add listeners to handle the fired events.  Maybe a work around would be to either change "broadcasting" to "fire_events" or to make events more like emails.

```
'events' => [
    'fire' => true,
    'broadcast' => false
],
```

Let me know your thoughts on these questions and I will add it to my PR when it hits. 

Thanks!

**Comment by socieboy** [comment]
Hey thank you so much for your time! 
I think you are right, sounds better idea to trigger events and handle the response by listeners. So you can work in that and I'm sure it would be better. So we can remove the broadcast of the repo.

**Comment by socieboy** [comment]
Seems pretty cool! The visual Style

**Comment by stygiansabyss** [comment]
Thank you :).  Its made to match the bootstrap dashboard theme.

One thing though was the question regarding storing the conversation and
replies differently. I can't do too much more without the answer to that.
If you could get back to me on that when you have time that would help me
greatly. Thanks!

**Comment by socieboy** [comment]
How do u want to store the conversation and replies?

**Comment by stygiansabyss** [comment]
As markdown. Then you parse them to HTML in the view file. Not when saving
them.

**Comment by stygiansabyss** [comment]
I submitted the PR for my initial changes (everything except editing and moving markdown conversion to the view).

My suggestion, if you agree, is to pull that in and tag version 1.1.0.  This will allow anyone using version 1 to have access to this code.

The editing of replies/conversations and moving markdown parsing to the views is done.  I think this should be tagged as version 2 when it is merged in mainly cause the change of moving markdown to the view from the database is a breaking change for anyone using this package.  So making it a new major version will avoid that problem.

Screenshots!
https://infinit.io/_/YJC9nzb Edit buttons
https://infinit.io/_/DhXTiPR Conversation edit modal
https://infinit.io/_/m47suJv Reply edit modal

**Comment by socieboy** [comment]
Ok! I'll take a look at your code as soon I can! And if everything goes well I will merge as you suggest!

**Comment by stygiansabyss** [comment]
https://infinit.io/_/UjZNcfe

Added a note that CommonMark mardown is supported to the various places a user can type in.  It links to http://commonmark.org/help/.  We can change the wording or all of it if you prefer.  But could be helpful for users.

**Comment by socieboy** [comment]
I merge that to the master branch since I don't support anymore the other versions with Laravel.
But from now that the forum seems very stable I'm going to tag your last changes and from there I will be more responsible with the next PR. I really appreciate your time to collaborate to this package.

**Comment by stygiansabyss** [comment]
I am currently using laravel 5.1.  So hopefully it will still work.

**Comment by socieboy** [comment]
T

2016-02-29 11:05 GMT-08:00 Travis Blasingame <notifications@github.com>:

**Comment by socieboy** [comment]
Well, Just remove the middleware web from the group routes.

2016-02-29 11:23 GMT-08:00 Frank Sepulveda <socieboy@gmail.com>:

**Comment by stygiansabyss** [comment]
Nah, the removal of SelfHandling from the events killed it.

**Comment by stygiansabyss** [comment]
Something to point out though, breaking changes should always be pushed to a new version.  Updating to 5.2 while still in the 1.* release is possibly something that will break existing packages.

**Comment by socieboy** [comment]
That's right! sorry about that... I already fix the issues and pushed.
