### ISSUE TITLE
Start Conversation

### ISSUE THREAD

**Issue by sugunak** [socieboy/forum#42]
I'am getting error when I run queue:listen after creation of new conversation.

[InvalidArgumentException]
No handler registered for command [Socieboy\Forum\Jobs\Conversations\StartConversation]

**Comment by socieboy** [comment]
What version of Laravel are you using?

**Comment by manshu** [comment]
disable these two events and then try.

'events'   => [
        'fire'      => false,
        'broadcast' => false,
    ],

**Comment by sugunak** [comment]
I am using Laravel 5.1 version. Also, tried by commenting those two events. Even though, no result.
