### ISSUE TITLE
Example code?

### ISSUE THREAD

**Issue by jonstavis** [socieboy/forum#45]
Is there an example project available for the demo hosted at http://socieboy.com/forum?

Thanks!

**Comment by socieboy** [comment]
No right now! I will create one.

**Comment by manshu** [comment]
I've an example of this installed on my site. https://www.thinkpmp.com/forum

**Comment by socieboy** [comment]
Do you want to share the code so I can put a link on the docs.

**Comment by manshu** [comment]
I used your repo to create this.

**Comment by socieboy** [comment]
I thought you have a repo with the code of your project.

**Comment by manshu** [comment]
No no, he asked for a demo, so i posted sample.

**Comment by jonstavis** [comment]
@socieboy is correct, I'm looking for a code example so I can see exactly how this gets integrated into a Laravel project.  I have a bunch of questions about setting this up and figured seeing an example that matches a working demo would be the easiest route.

**Comment by socieboy** [comment]
I don't have the source code of the demo page right now! I will upload it as soon I have a chance! @jonstavis

**Comment by manshu** [comment]
I can upload it, it's really easy.
