### ISSUE TITLE
Edit Reply not working

### ISSUE THREAD

**Issue by SamuelYute** [socieboy/forum#47]
Hey guys... i'm new to laravel...When you try to edit a reply, in the edit modal it shows you the message of the first reply in that conversation and when you try to edit that...it actually posts but update doesn't go to the intended
This happens for every reply in a particular conversation.You  can try to edit any reply and it will only view and edit the first reply on the thread.
i tried to use socieboy.com but the same problem is also there

Please help out

**Comment by socieboy** [comment]
No supporting this package anymore
