### ISSUE TITLE
PostReply issue

### ISSUE THREAD

**Issue by gealberto** [socieboy/forum#7]
FatalErrorException in PostReply.php line 14:
Class 'Socieboy\Forum\Jobs\Replies\Job' not found

I use this class: // use Illuminate \ Queue \ Jobs \ Job; but also still it has problems..

**Comment by socieboy** [comment]
What version of Laravel are you using?

**Comment by socieboy** [comment]
You should update the forum to dev-master version!

**Comment by override-chaos** [comment]
Check the demo forum, it uses the latest code with no modifications and it's working currently.

http://forum.laravel.org.uk/

**Comment by gealberto** [comment]
The 5.0.23

Germán Alberto Zarza Caro


Date: Thu, 18 Jun 2015 12:41:33 -0700

**Comment by socieboy** [comment]
Forum works with 5.1
